param(
    [string]$RomImage = "s3built.bin",
    [string]$OutputDirectory = "SegaCD/build/modules",
    [int]$MaxModuleBytes = 61440,
    [int]$SectorBytes = 2048,
    [int]$LoadModuleCommandId = 206
)

$ErrorActionPreference = "Stop"
$root = (Get-Location).Path
$romPath = Join-Path $root $RomImage
$outputPath = Join-Path $root $OutputDirectory
if (!(Test-Path -LiteralPath $romPath)) { throw "Sonic 3 ROM not found: $romPath. Build s3built.bin first." }
if ($MaxModuleBytes -le 0 -or $MaxModuleBytes -ge 65536) { throw "MaxModuleBytes must be less than the 64 KiB module-size field." }
if ($SectorBytes -ne 2048 -or ($MaxModuleBytes % $SectorBytes) -ne 0) { throw "MaxModuleBytes must be a multiple of the 2048-byte CD sector size." }
if ($LoadModuleCommandId -lt 1 -or $LoadModuleCommandId -gt 255) { throw "LoadModuleCommandId must fit in the Sub CPU command byte." }

$resolvedRoot = (Resolve-Path -LiteralPath $root).Path.TrimEnd('\') + '\'
New-Item -ItemType Directory -Force -Path $outputPath | Out-Null
$resolvedOutput = (Resolve-Path -LiteralPath $outputPath).Path
if (!$resolvedOutput.StartsWith($resolvedRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "OutputDirectory must stay inside the Sonic 3 workspace: $resolvedOutput"
}

$rom = [System.IO.File]::ReadAllBytes((Resolve-Path -LiteralPath $romPath).Path)
if ($rom.Length -ne 0x200000) { throw "Expected a 2 MiB Sonic 3 ROM image, found $($rom.Length) bytes." }
$count = [int][Math]::Ceiling($rom.Length / [double]$MaxModuleBytes)
if ($count -gt 100) { throw "The ISO 9660 module name range S3R00.BIN-S3R99.BIN was exceeded." }

# Delete only this script's old outputs, and only after every input and size check.
Get-ChildItem -LiteralPath $resolvedOutput -Filter "S3R*.BIN" -File | Remove-Item -Force
$moduleRows = [System.Collections.Generic.List[object]]::new()
for ($moduleId = 0; $moduleId -lt $count; $moduleId++) {
    $offset = $moduleId * $MaxModuleBytes
    $length = [Math]::Min($MaxModuleBytes, $rom.Length - $offset)
    $name = "S3R{0:D2}.BIN" -f $moduleId
    $bytes = [byte[]]::new($length)
    [Array]::Copy($rom, $offset, $bytes, 0, $length)
    [System.IO.File]::WriteAllBytes((Join-Path $resolvedOutput $name), $bytes)
    $moduleRows.Add([pscustomobject]@{
        ModuleId = $moduleId
        ModuleFile = $name
        ROMStart = $offset
        ROMEndExclusive = $offset + $length
        Bytes = $length
    })
}

$moduleRows | Export-Csv -LiteralPath (Join-Path $resolvedOutput "S3CD_RomModules.csv") -NoTypeInformation -Encoding UTF8
$index = [System.Collections.Generic.List[string]]::new()
$index.Add("; Generated by SegaCD/Build-RomModules.ps1. ROM end addresses are exclusive.")
$index.Add("S3CD_RomSegmentSize = $MaxModuleBytes")
$index.Add("S3CD_RomSegmentIndex:")
foreach ($row in $moduleRows) {
    $index.Add("`tdc.l `$" + $row.ROMStart.ToString('X8') + ", `$" + $row.ROMEndExclusive.ToString('X8'))
    $index.Add("`tdc.w $($row.ModuleId), 0")
}
[System.IO.File]::WriteAllLines((Join-Path $root "SegaCD\generated\S3CD_RomSegmentIndex.asm"), $index)

$asm = [System.Collections.Generic.List[string]]::new()
$asm.Add("; Generated by SegaCD/Build-RomModules.ps1. Do not edit.")
$asm.Add("S3CD_ModuleCount = $count")
[System.IO.File]::WriteAllLines((Join-Path $resolvedOutput "S3CD_SPXModules.asm"), $asm)

$defs = @(
    "; Generated by SegaCD/Build-RomModules.ps1. Do not edit."
    "S3CD_ModuleCount = $count"
    "; SCMD_DUMMY1 slot copied from the analyzed Sonic CD command table."
    "S3CD_LoadModuleCommand = $LoadModuleCommandId"
)
[System.IO.File]::WriteAllLines((Join-Path $root "SegaCD\generated\S3CD_ModuleDefs.asm"), $defs)

Write-Host "Split $RomImage ($($rom.Length) bytes) into $count disc-loadable ROM segments."
foreach ($row in $moduleRows) {
    Write-Host ("{0} ROM 0x{1:X6}-0x{2:X6}  {3,6} bytes" -f $row.ModuleFile,$row.ROMStart,$row.ROMEndExclusive,$row.Bytes)
}
