param(
    [string]$Source = "SegaCD/Runtime/IPX.asm",
    [string]$OutputDirectory = "SegaCD/build/runtime",
    [string]$OutputModule = "IPX___.MMD"
)

$ErrorActionPreference = "Stop"
$root = (Resolve-Path -LiteralPath ".").Path
$sourcePath = (Resolve-Path -LiteralPath $Source).Path
$outputPath = Join-Path $root $OutputDirectory
$resolvedBuild = (Resolve-Path -LiteralPath "SegaCD/build").Path.TrimEnd('\') + '\'
New-Item -ItemType Directory -Force -Path $outputPath | Out-Null
$outputPath = (Resolve-Path -LiteralPath $outputPath).Path
if (!$outputPath.StartsWith($resolvedBuild, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "Runtime outputs must stay under SegaCD/build: $outputPath"
}

$assembler = (Resolve-Path -LiteralPath "build_tools/Windows-x86/asw.exe").Path
$p2bin = (Resolve-Path -LiteralPath "build_tools/Windows-x86/p2bin.exe").Path
$assemblyPath = Join-Path $outputPath "IPX.asm"
$objectPath = Join-Path $outputPath "IPX.p"
$rawModulePath = Join-Path $outputPath "IPX.raw.bin"
$modulePath = Join-Path $outputPath $OutputModule
$romModulesPath = Join-Path $root "SegaCD/build/modules"
$romModules = @(Get-ChildItem -LiteralPath $romModulesPath -Filter "S3R??.BIN" -File | Sort-Object Name)
if ($romModules.Count -ne 35) { throw "Runtime expects the 35 generated Sonic 3 ROM modules; found $($romModules.Count)." }
$assetModules = @(Get-ChildItem -LiteralPath $romModulesPath -Filter "S3M??.BIN" -File | Sort-Object Name)
if ($assetModules.Count -eq 0) { throw "Runtime expects generated Sonic 3 asset modules." }
$discModules = @($romModules) + @($assetModules)
$checksumLines = [System.Collections.Generic.List[string]]::new()
$checksumLines.Add("; Generated by SegaCD/Build-Runtime.ps1. Do not edit.")
$checksumLines.Add("S3CD_RomModuleCount = $($romModules.Count)")
$checksumLines.Add("S3CD_AssetModuleCount = $($assetModules.Count)")
$checksumLines.Add("S3CD_ModuleCount = $($discModules.Count)")
$checksumLines.Add("S3CD_DiscModuleTable:")
for ($moduleId = 0; $moduleId -lt $discModules.Count; $moduleId++) {
    $module = $discModules[$moduleId]
    if ($moduleId -lt $romModules.Count) {
        $expectedName = "S3R{0:D2}.BIN" -f $moduleId
    } else {
        $assetId = $moduleId - $romModules.Count
        $expectedName = "S3M{0:D2}.BIN" -f $assetId
    }
    if ($module.Name -ne $expectedName) { throw "Runtime disc modules must be contiguous: expected $expectedName, found $($module.Name)." }
    $romSegment = [System.IO.File]::ReadAllBytes($module.FullName)
    if (($romSegment.Length % 2) -ne 0 -or $romSegment.Length -ge 65536) { throw "$expectedName must have an even byte count below the 64 KiB status-register limit." }
    $checksum = 0
    for ($i = 0; $i -lt $romSegment.Length; $i += 2) {
        $checksum = ($checksum + ($romSegment[$i] * 256) + $romSegment[$i + 1]) -band 0xFFFF
    }
    $checksumLines.Add(("`tdc.w {0}, `$" -f $romSegment.Length) + $checksum.ToString("X4"))
}
$checksumInclude = Join-Path $outputPath "S3CD_RuntimeChecksums.i"
[System.IO.File]::WriteAllLines($checksumInclude, $checksumLines)
Copy-Item -LiteralPath $sourcePath -Destination $assemblyPath -Force

& $assembler -xx -n -q -A -L -U -E -i . $assemblyPath
if ($LASTEXITCODE -ne 0 -or !(Test-Path -LiteralPath $objectPath -PathType Leaf)) {
    throw "AS assembled the Sega CD runtime with errors. See $outputPath/IPX.log"
}

& $p2bin "-p=0" $objectPath $rawModulePath
if ($LASTEXITCODE -ne 0 -or !(Test-Path -LiteralPath $rawModulePath -PathType Leaf)) {
    throw "p2bin failed to convert the Sega CD runtime MMD."
}

$rawBytes = [System.IO.File]::ReadAllBytes($rawModulePath)
if ($rawBytes.Length -gt 4096) { throw "IPX runtime is larger than its 4 KiB MMD allocation: $($rawBytes.Length) bytes." }
if ($rawBytes.Length -lt 0x100) { throw "IPX runtime is missing the 256-byte MMD header block." }
$expectedHeader = "000000FF000003FF"
$actualHeader = [BitConverter]::ToString($rawBytes[0..7]).Replace("-", "")
$entryAddress = ([uint32]$rawBytes[8] -shl 24) -bor ([uint32]$rawBytes[9] -shl 16) -bor ([uint32]$rawBytes[10] -shl 8) -bor [uint32]$rawBytes[11]
if ($actualHeader -ne $expectedHeader -or $entryAddress -lt 0x00FF0000 -or $entryAddress -ge 0x00FF1000 -or
    $rawBytes[12] -ne 0 -or $rawBytes[13] -ne 0 -or $rawBytes[14] -ne 0 -or $rawBytes[15] -ne 0) {
    throw "IPX MMD header invalid: found $actualHeader, entry 0x$($entryAddress.ToString('X8'))."
}

$moduleBytes = [byte[]]::new(4096)
[Array]::Copy($rawBytes, $moduleBytes, $rawBytes.Length)
[System.IO.File]::WriteAllBytes($modulePath, $moduleBytes)
Write-Host "Assembled Sega CD Main CPU runtime: $modulePath ($($moduleBytes.Length) bytes; source payload $($rawBytes.Length - 0x100) bytes; validates $($discModules.Count) ROM/asset modules)."
