param(
    [string]$Manifest = "SegaCD/s3-asset-manifest.csv",
    [string]$OutputDirectory = "SegaCD/build/assets"
)

$ErrorActionPreference = "Stop"
$root = (Get-Location).Path
$manifestPath = Join-Path $root $Manifest
$outputPath = Join-Path $root $OutputDirectory
if (!(Test-Path -LiteralPath $manifestPath)) {
    throw "Asset manifest not found: $manifestPath"
}
New-Item -ItemType Directory -Force -Path $outputPath | Out-Null

$assets = Import-Csv -LiteralPath $manifestPath | Sort-Object {
    [Convert]::ToInt32($_.ROMStart.Substring(2), 16)
}
$packFile = Join-Path $outputPath "S3ART.BIN"
$indexFile = Join-Path $outputPath "S3ART_Index.asm"
$csvFile = Join-Path $outputPath "S3ART_Index.csv"
$romSize = 0x200000
$stream = [System.IO.File]::Create($packFile)
$index = [System.Collections.Generic.List[object]]::new()
try {
    $stream.SetLength($romSize)
    foreach ($asset in $assets) {
        $source = Join-Path $root ($asset.Asset -replace '/', '\')
        if (!(Test-Path -LiteralPath $source)) {
            throw "Asset not found: $($asset.Asset)"
        }

        $romAddress = [Convert]::ToInt32($asset.ROMStart.Substring(2), 16)
        $sourceBytes = [System.IO.File]::ReadAllBytes($source)
        if ($sourceBytes.Length -ne [int]$asset.SpanBytes) {
            throw "Asset length mismatch for $($asset.Label): manifest=$($asset.SpanBytes), file=$($sourceBytes.Length)"
        }

        $discOffset = $romAddress
        $index.Add([pscustomobject]@{
            ROMStart = $romAddress
            Length = $sourceBytes.Length
            DiscOffset = $discOffset
            Label = $asset.Label
            Asset = $asset.Asset
        })
        if (($romAddress + $sourceBytes.Length) -gt $romSize) {
            throw "Asset exceeds the 2 MiB Sonic 3 ROM address space: $($asset.Label)"
        }
        $stream.Position = $romAddress
        $stream.Write($sourceBytes, 0, $sourceBytes.Length)
    }
}
finally {
    $stream.Dispose()
}

$asmLines = [System.Collections.Generic.List[string]]::new()
$asmLines.Add("; Generated by SegaCD/Build-AssetPack.ps1. Disc offsets equal original ROM offsets.")
$asmLines.Add("S3CD_AssetCount = $($index.Count)")
$asmLines.Add("S3CD_AssetIndex:")
foreach ($entry in $index) {
    $asmLines.Add("`tdc.l `$" + $entry.ROMStart.ToString("X6") + ", `$" + $entry.DiscOffset.ToString("X8") + ", `$" + $entry.Length.ToString("X8"))
}
[System.IO.File]::WriteAllLines($indexFile, $asmLines)
$index | ForEach-Object {
    [pscustomobject]@{
        ROMStart = "0x{0:X6}" -f $_.ROMStart
        DiscOffset = "0x{0:X8}" -f $_.DiscOffset
        Length = $_.Length
        Label = $_.Label
        Asset = $_.Asset
    }
} | Export-Csv -LiteralPath $csvFile -NoTypeInformation -Encoding UTF8

Write-Host "Packed $($index.Count) assets into $packFile ($((Get-Item -LiteralPath $packFile).Length) bytes)."
Write-Host "Generated ROM-address index: $indexFile"
