param(
    [string]$ModulesDirectory = "SegaCD/build/modules",
    [string]$OutputDirectory = "SegaCD/Runtime/SubCPU"
)

$ErrorActionPreference = "Stop"
$root = (Resolve-Path -LiteralPath ".").Path
$modulesPath = Join-Path $root $ModulesDirectory
$outputPath = Join-Path $root $OutputDirectory
if (!(Test-Path -LiteralPath $modulesPath -PathType Container)) { throw "Sonic 3 disc modules not found: $modulesPath" }
New-Item -ItemType Directory -Force -Path $outputPath | Out-Null
$resolvedOutput = (Resolve-Path -LiteralPath $outputPath).Path
$resolvedRoot = (Resolve-Path -LiteralPath (Join-Path $root "SegaCD/Runtime")).Path.TrimEnd('\') + '\'
if (!$resolvedOutput.StartsWith($resolvedRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "Sub CPU generated source must stay inside SegaCD/Runtime: $resolvedOutput"
}

$romModules = @(Get-ChildItem -LiteralPath $modulesPath -Filter "S3R??.BIN" -File | Sort-Object Name)
$assetModules = @(Get-ChildItem -LiteralPath $modulesPath -Filter "S3M??.BIN" -File | Sort-Object Name)
$assetRowsPath = Join-Path $modulesPath "S3CD_Assets.csv"
if (!(Test-Path -LiteralPath $assetRowsPath -PathType Leaf)) { throw "Asset lookup table not found: $assetRowsPath" }
$assetRows = @(Import-Csv -LiteralPath $assetRowsPath)
if ($romModules.Count -ne 35) { throw "Expected 35 Sonic 3 ROM segments; found $($romModules.Count)." }
if ($assetModules.Count -eq 0 -or $assetModules.Count -gt 100) { throw "Expected 1-100 Sonic 3 asset modules; found $($assetModules.Count)." }
if ($assetRows.Count -eq 0) { throw "No Sonic 3 assets were indexed for runtime loading." }

for ($id = 0; $id -lt $romModules.Count; $id++) {
    $expected = "S3R{0:D2}.BIN" -f $id
    if ($romModules[$id].Name -ne $expected) { throw "ROM modules are not contiguous: expected $expected, found $($romModules[$id].Name)." }
}
for ($id = 0; $id -lt $assetModules.Count; $id++) {
    $expected = "S3M{0:D2}.BIN" -f $id
    if ($assetModules[$id].Name -ne $expected) { throw "Asset modules are not contiguous: expected $expected, found $($assetModules[$id].Name)." }
    if ($assetModules[$id].Length -ge 65536) { throw "$expected exceeds the 16-bit Sub CPU file-size field." }
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("; Generated by SegaCD/Build-SubCPU.ps1. Do not edit.")
$lines.Add("S3CD_RomModuleCount = $($romModules.Count)")
$lines.Add("S3CD_AssetModuleCount = $($assetModules.Count)")
$lines.Add("S3CD_AssetCount = $($assetRows.Count)")
$lines.Add("S3CD_ModuleCount = $($romModules.Count + $assetModules.Count)")
$includePath = Join-Path $resolvedOutput "S3CD_ModuleFiles.asm"
[System.IO.File]::WriteAllLines($includePath, $lines)

$lookupLines = [System.Collections.Generic.List[string]]::new()
$lookupBytes = [System.Collections.Generic.List[byte]]::new()
$lookupLines.Add("; Generated by SegaCD/Build-SubCPU.ps1. Do not edit.")
$lookupLines.Add("S3CD_AssetCount = $($assetRows.Count)")
$lookupLines.Add("S3CD_AssetLookup:")
foreach ($asset in $assetRows) {
    $romStart = [Convert]::ToInt32($asset.ROMStart.Substring(2), 16)
    $moduleOffset = [int]$asset.ModuleOffset
    $length = [int]$asset.Length
    $moduleId = [int]$asset.ModuleId
    if ($moduleOffset -lt 0 -or $moduleOffset -gt 65535 -or $length -le 0 -or $length -gt 65535) {
        throw "Asset lookup entry is outside the loader's 16-bit window: $($asset.Label)."
    }
    $lookupLines.Add(("`tdc.l `$" + $romStart.ToString('X6') + ", `$" + $moduleOffset.ToString('X4') + ", `$" + $length.ToString('X4')))
    $lookupLines.Add(("`tdc.w $moduleId, 0 ; $($asset.Label)"))

    foreach ($value in @($romStart, $moduleOffset, $length)) {
        [void]$lookupBytes.Add([byte](($value -shr 24) -band 0xFF))
        [void]$lookupBytes.Add([byte](($value -shr 16) -band 0xFF))
        [void]$lookupBytes.Add([byte](($value -shr 8) -band 0xFF))
        [void]$lookupBytes.Add([byte]($value -band 0xFF))
    }
    [void]$lookupBytes.Add([byte](($moduleId -shr 8) -band 0xFF))
    [void]$lookupBytes.Add([byte]($moduleId -band 0xFF))
    [void]$lookupBytes.Add([byte]0)
    [void]$lookupBytes.Add([byte]0)
}
$lookupPath = Join-Path $resolvedOutput "S3CD_AssetLookup.asm"
[System.IO.File]::WriteAllLines($lookupPath, $lookupLines)
if ($lookupBytes.Count -ne ($assetRows.Count * 16)) { throw "Asset lookup binary has an invalid record size: $($lookupBytes.Count) bytes." }
$lookupBinaryPath = Join-Path $modulesPath "S3ALOOK.BIN"
[System.IO.File]::WriteAllBytes($lookupBinaryPath, $lookupBytes.ToArray())
Write-Host "Prepared Sub CPU loader: $($romModules.Count) ROM modules, $($assetModules.Count) asset modules, $($assetRows.Count) indexed assets."
